---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: gpbackup
  type: git
  source:
    uri: https://github.com/greenplum-db/gpbackup
    branch: master
    ignore_paths:
    - ci

- name: gpbackup-ci
  type: git
  source:
    uri: https://github.com/greenplum-db/gpbackup
    branch: master
    paths:
    - ci

- name: gpdb_src
  type: git
  source:
    uri: https://github.com/greenplum-db/gpdb
    branch: 5X_STABLE
    tag_filter: 5.*

- name: bin_gpdb_master
  type: s3
  source:
      bucket: gpdb5-concourse-builds
      versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz
      region_name: us-west-2
      access_key_id: {{bucket-access-key-id}}
      secret_access_key: {{bucket-secret-access-key}}

- name: bin_gpdb_5x_stable
  type: s3
  source:
      bucket: gpdb5-release-builds
      versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz
      region_name: us-west-2
      access_key_id: {{bucket-access-key-id}}
      secret_access_key: {{bucket-secret-access-key}}

- name: bin_gpdb_43_stable
  type: s3
  source:
      bucket: gpdb-4.3-stable-concourse
      versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz
      region_name: us-west-2
      access_key_id: {{gpdb4-bucket-access-key-id}}
      secret_access_key: {{gpdb4-bucket-secret-access-key}}

- name: ccp_src
  type: git
  source:
    branch: {{ccp-git-branch}}
    private_key: {{ccp-git-key}}
    uri: {{ccp-git-remote}}
    tag_filter: 1.0.0-beta.1

- name: terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
    storage:
      access_key_id: {{tf-machine-access-key-id}}
      secret_access_key: {{tf-machine-secret-access-key}}
      region_name: {{aws-region}}
      bucket: gpdb5-pipeline-dynamic-terraform
      bucket_path: {{tf-bucket-path}}

jobs:
- name: units
  serial: true
  plan:
  - aggregate:
    - get: gpbackup
      trigger: true
    - get: gpbackup-ci
  - task: unit-tests
    file: gpbackup-ci/ci/tasks/unit-tests.yml

- name: integrations-master
  serial: true
  plan:
  - aggregate:
    - get: gpbackup
      trigger: true
    - get: gpbackup-ci
    - get: bin_gpdb_master
    - get: ccp_src
    - get: gpdb_src
  - put: terraform
    params:
      <<: *ccp_create_params
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      gpdb_binary: bin_gpdb_master
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: integration-tests
    file: gpbackup-ci/ci/tasks/integration-tests.yml
    on_failure:
      <<: *ccp_destroy
  - *ccp_destroy

- name: integrations-GPDB5
  serial: true
  plan:
  - aggregate:
    - get: gpbackup
      trigger: true
    - get: gpbackup-ci
    - get: bin_gpdb_5x_stable
    - get: ccp_src
    - get: gpdb_src
  - put: terraform
    params:
      <<: *ccp_create_params
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      gpdb_binary: bin_gpdb_5x_stable
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: integration-tests
    file: gpbackup-ci/ci/tasks/integration-tests.yml
    on_failure:
      <<: *ccp_destroy
  - *ccp_destroy

- name: integrations-GPDB4.3
  serial: true
  plan:
  - aggregate:
    - get: gpbackup
      trigger: true
    - get: gpbackup-ci
    - get: bin_gpdb_43_stable
    - get: ccp_src
    - get: gpdb_src
  - put: terraform
    params:
      <<: *ccp_create_params
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    input_mapping:
      gpdb_binary: bin_gpdb_43_stable
      gpdb_src: gpdb_src
    on_failure:
      <<: *ccp_destroy
  - task: integration-tests
    file: gpbackup-ci/ci/tasks/integration-tests.yml
    on_failure:
      <<: *ccp_destroy
  - *ccp_destroy

ccp_create_params_anchor: &ccp_create_params
  action: create
  delete_on_failure: true
  generate_random_name: true
  terraform_source: ccp_src/aws/
  vars:
    aws_instance-node-instance_type: t2.medium

ccp_destroy_anchor: &ccp_destroy
  put: terraform
  params:
    action: destroy
    env_name_file: terraform/name
    terraform_source: ccp_src/aws/
    vars:
      aws_instance-node-instance_type: t2.micro
  get_params:
    action: destroy

debug_sleep_anchor: &debug_sleep
  do:
  - task: debug_sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      run:
        path: 'sh'
        args: ['-c', 'sleep 2h']
  ensure:
    <<: *ccp_destroy
